// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW74S_nAnI_GNHW_IY3EbF7VVql1JSZDA',
    appId: '1:616077887688:web:9028be59cb97907e8a3dfd',
    messagingSenderId: '616077887688',
    projectId: 'couplemood-507e6',
    authDomain: 'couplemood-507e6.firebaseapp.com',
    storageBucket: 'couplemood-507e6.firebasestorage.app',
    measurementId: 'G-ETW0F9X4X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwMhoJMOiENNvMTFpvv5HAUx7zDIBdmO4',
    appId: '1:616077887688:android:e2f5809e37bff0568a3dfd',
    messagingSenderId: '616077887688',
    projectId: 'couplemood-507e6',
    storageBucket: 'couplemood-507e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPxpnWvkxS0wp-Hzk-f6N3Xlt1FcCZjRI',
    appId: '1:616077887688:ios:72409f27d0717adf8a3dfd',
    messagingSenderId: '616077887688',
    projectId: 'couplemood-507e6',
    storageBucket: 'couplemood-507e6.firebasestorage.app',
    iosBundleId: 'com.example.coupleMoodMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPxpnWvkxS0wp-Hzk-f6N3Xlt1FcCZjRI',
    appId: '1:616077887688:ios:72409f27d0717adf8a3dfd',
    messagingSenderId: '616077887688',
    projectId: 'couplemood-507e6',
    storageBucket: 'couplemood-507e6.firebasestorage.app',
    iosBundleId: 'com.example.coupleMoodMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW74S_nAnI_GNHW_IY3EbF7VVql1JSZDA',
    appId: '1:616077887688:web:e5afee19633ef65d8a3dfd',
    messagingSenderId: '616077887688',
    projectId: 'couplemood-507e6',
    authDomain: 'couplemood-507e6.firebaseapp.com',
    storageBucket: 'couplemood-507e6.firebasestorage.app',
    measurementId: 'G-EQJ5JR146J',
  );

}